# action.yml
name: 'Katalon-Studio'
description: 'KS Action for running test'
inputs:
  ks_command:
    description: 'katalon parameter'
    required: true
  ks_api_key:
    description: 'api key'
    required: true
outputs:
  status:
      description: 'Status of running KS Test'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.ks_command}}
    - ${{ inputs.ks_api_key}}